@GameStore.Api_HostAddress = http://localhost:5235

# GET {{GameStore.Api_HostAddress}}/weatherforecast/
# Accept: application/json

###
GET {{GameStore.Api_HostAddress}}/games/
Accept: application/json

###
GET {{GameStore.Api_HostAddress}}/games/3
Accept: application/json

###
POST {{GameStore.Api_HostAddress}}/games/
Accept: application/json
Content-Type:  application/json
{
  "name": "Final Fantasy XIV",
  "genreId": 2,
  "price": 59.99,
  "releasedDate": "2010-09-30"
}

###
PUT {{GameStore.Api_HostAddress}}/games/1
# Accept: application/json
Content-Type:  application/json
{
  "name": "Mortal Combat",
  "genre": "Combat",
  "price": 55.99,
  "releasedDate": "22-10-16"
}

###
DELETE {{GameStore.Api_HostAddress}}/games/3
Accept: application/json